/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taquin02;

import java.util.Arrays;

/**
 *
 * @author BMMed
 */
public class views extends javax.swing.JFrame {

    boolean btnMode =true;
     public int[] tabManhatan = {36, 12, 12, 4, 1, 1, 4, 1, 0};
    public int constManhatan = 4;
    String res="";
    /**
     * Creates new form views
     */
    public views() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnMan01 = new javax.swing.JRadioButton();
        btnMan02 = new javax.swing.JRadioButton();
        btnMan03 = new javax.swing.JRadioButton();
        btnMan04 = new javax.swing.JRadioButton();
        btnMan05 = new javax.swing.JRadioButton();
        btnMan06 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        mat11 = new javax.swing.JTextField();
        mat31 = new javax.swing.JTextField();
        mat22 = new javax.swing.JTextField();
        mat32 = new javax.swing.JTextField();
        mat21 = new javax.swing.JTextField();
        mat12 = new javax.swing.JTextField();
        mat33 = new javax.swing.JTextField();
        mat23 = new javax.swing.JTextField();
        mat13 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        testR = new javax.swing.JTextArea();
        btnResoudre = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(btnMan01);
        btnMan01.setSelected(true);
        btnMan01.setText("Manhatan 01");
        btnMan01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMan01ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnMan02);
        btnMan02.setText("Manhatan 02");
        btnMan02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMan02ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnMan03);
        btnMan03.setText("Manhatan 03");
        btnMan03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMan03ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnMan04);
        btnMan04.setText("Manhatan 04");
        btnMan04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMan04ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnMan05);
        btnMan05.setText("Manhatan 05");
        btnMan05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMan05ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnMan06);
        btnMan06.setText("Manhatan 06");
        btnMan06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMan06ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMan05)
                    .addComponent(btnMan06)
                    .addComponent(btnMan04)
                    .addComponent(btnMan03)
                    .addComponent(btnMan02)
                    .addComponent(btnMan01))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMan01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMan02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMan03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMan04)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMan05)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMan06))
        );

        mat11.setText("1");
        mat11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat11ActionPerformed(evt);
            }
        });

        mat31.setText("4");
        mat31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat31ActionPerformed(evt);
            }
        });

        mat22.setText("7");
        mat22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat22ActionPerformed(evt);
            }
        });

        mat32.setText("2");
        mat32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat32ActionPerformed(evt);
            }
        });

        mat21.setText("5");
        mat21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat21ActionPerformed(evt);
            }
        });

        mat12.setText("3");
        mat12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat12ActionPerformed(evt);
            }
        });

        mat33.setText("0");
        mat33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat33ActionPerformed(evt);
            }
        });

        mat23.setText("6");
        mat23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat23ActionPerformed(evt);
            }
        });

        mat13.setText("8");
        mat13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(mat11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mat12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mat13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mat31, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mat21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(mat32, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mat33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(mat22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mat23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        testR.setColumns(20);
        testR.setRows(5);
        jScrollPane1.setViewportView(testR);

        btnResoudre.setText("Resoudre");
        btnResoudre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResoudreMouseClicked(evt);
            }
        });
        btnResoudre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResoudreActionPerformed(evt);
            }
        });

        jButton1.setText("Rejouer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btnResoudre))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResoudre)
                    .addComponent(jButton1))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mat11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat11ActionPerformed

    private void mat12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat12ActionPerformed

    private void mat13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat13ActionPerformed

    private void mat21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat21ActionPerformed

    private void mat22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat22ActionPerformed

    private void mat23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat23ActionPerformed

    private void mat31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat31ActionPerformed

    private void mat32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat32ActionPerformed

    private void mat33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat33ActionPerformed

    private void btnResoudreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResoudreActionPerformed
        
        res="";
          if(btnMan01.isSelected()){
            int[] inter = {36, 12, 12, 4, 1, 1, 4, 1, 0};
            tabManhatan = inter.clone();
            constManhatan = 4;
            res+="-SELON MANHATAN 01";
            res+="\n- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * \n";
          }else if(btnMan02.isSelected()){
            int[] inter = {8, 7, 6, 5, 4, 3, 2 ,1, 0};
            tabManhatan = inter.clone();
            constManhatan = 1;
            res+="-SELON MANHATAN 02";
            res+="\n- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * \n";
          }else if(btnMan03.isSelected()){
            int[] inter = {8, 7, 6, 5, 4, 3, 2 ,1, 0};
            tabManhatan = inter.clone();
            constManhatan = 4;
            res+="-SELON MANHATAN 03";
            res+="\n- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * \n";
          }else if(btnMan04.isSelected()){
            int[] inter = {8, 7, 6, 5, 4, 3, 2 ,1, 0};
            tabManhatan = inter.clone();
            constManhatan = 1;
            res+="-SELON MANHATAN 04";
            res+="\n- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * \n";
          }else if(btnMan05.isSelected()){
            int[] inter = {8, 7, 6, 5, 4, 3, 2 ,1, 0};
            tabManhatan = inter.clone();
            constManhatan = 4;
            res+="-SELON MANHATAN 05";
            res+="\n- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * \n";
          }else if(btnMan06.isSelected()){
            int[] inter = {1, 1, 1, 1, 1, 1, 1 ,1, 0};
            tabManhatan = inter.clone();
            constManhatan = 1;
            res+="-SELON MANHATAN 06";
            res+="\n- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * \n";
          }
   
  
       int[][] m= new int[3][3];
    
   
                m[0][0]=Integer.parseInt(mat11.getText());
                m[0][1]=Integer.parseInt(mat12.getText());
                m[0][2]=Integer.parseInt(mat13.getText());
                
                m[1][0]=Integer.parseInt(mat21.getText());
                m[1][1]=Integer.parseInt(mat22.getText());
                m[1][2]=Integer.parseInt(mat23.getText());
                
                m[2][0]=Integer.parseInt(mat31.getText());
                m[2][1]=Integer.parseInt(mat32.getText());
                m[2][2]=Integer.parseInt(mat33.getText());
                

    Etat e=new Etat();e.setMatrix(m);
    Metrier metier=new Metrier();
   
   res+=metier.Research(e,tabManhatan,constManhatan);

   testR.setText(res);
   
   

   // TODO add your handling code here:
    }//GEN-LAST:event_btnResoudreActionPerformed

    private void btnResoudreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResoudreMouseClicked

    }//GEN-LAST:event_btnResoudreMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       mat11.setText("");
       mat12.setText("");
       mat13.setText("");
       mat21.setText("");
       mat22.setText("");
       mat23.setText("");
       mat31.setText("");
       mat32.setText("");
       mat33.setText("");
       testR.setText("");     
       btnMan01.setSelected(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMan01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMan01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMan01ActionPerformed

    private void btnMan02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMan02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMan02ActionPerformed

    private void btnMan03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMan03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMan03ActionPerformed

    private void btnMan04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMan04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMan04ActionPerformed

    private void btnMan05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMan05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMan05ActionPerformed

    private void btnMan06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMan06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMan06ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new views().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnMan01;
    private javax.swing.JRadioButton btnMan02;
    private javax.swing.JRadioButton btnMan03;
    private javax.swing.JRadioButton btnMan04;
    private javax.swing.JRadioButton btnMan05;
    private javax.swing.JRadioButton btnMan06;
    private javax.swing.JButton btnResoudre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mat11;
    private javax.swing.JTextField mat12;
    private javax.swing.JTextField mat13;
    private javax.swing.JTextField mat21;
    private javax.swing.JTextField mat22;
    private javax.swing.JTextField mat23;
    private javax.swing.JTextField mat31;
    private javax.swing.JTextField mat32;
    private javax.swing.JTextField mat33;
    private javax.swing.JTextArea testR;
    // End of variables declaration//GEN-END:variables
}
